[workspace]
members = [
    "crates/rustyfx",
    "crates/rustyfx-core",
    "misc/curr_unusable_crates/rustyfx-convert",
    "misc/curr_unusable_crates/rustyfx-crypto",
]

exclude = [
    "misc/curr_unusable_crates/rustyfx-convert",
    "misc/curr_unusable_crates/rustyfx-crypto",
]